[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Brook Heisler"]
name = "criterion-stats"
version = "0.1.0"

description = "Criterion's statistics library"
repository = "https://github.com/japaric/stats.rs"
readme = "README.md"
keywords = ["statistics", "stats", "criterion"]
license = "MIT/Apache-2.0"

[dependencies]
cast = "0.1.0"
floaty = "0.1.0"
num_cpus = "0.2.10"
rand = "0.3.13"
thread-scoped = "1.0.1"

[dev-dependencies]
approx = "0.1.0"
itertools = "0.4.7"
quickcheck = "0.4.1"
quickcheck_macros = "0.4.1"

[badges]
travis-ci = { repository = "japaric/stats.rs" }
appveyor = { repository = "japaric/stats.rs", id = "pmrliloj5nu3prw7" }
maintenance = { status = "actively-maintained" }
